import {Inter, Chakra_Petch, Teko} from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});
const chakra = Chakra_Petch({
  subsets: ['latin'],
  variable: '--font-chakra',
  style: ['italic', 'normal'],
  weight: ['300', '400', '500', '600', '700'],
});

const teko = Teko({
  subsets: ['latin'],
  variable: '--font-teko',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
 
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={`${chakra.variable} ${inter.className} ${teko.variable}`}>
        {/* <Navbar /> */}
        {/* <Footer /> */}
        {children}
      </body>
    </html>
  );
}
