import {Inter, Chakra_Petch, Teko} from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Head from 'next/head';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});
const chakra = Chakra_Petch({
  subsets: ['latin'],
  variable: '--font-chakra',
  style: ['italic', 'normal'],
  weight: ['300', '400', '500', '600', '700'],
});

const teko = Teko({
  subsets: ['latin'],
  variable: '--font-teko',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <Head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, viewport-fit=contain, user-scalable=no'
        />
      </Head>
      <body className={`${chakra.variable} ${inter.className} ${teko.variable}`}>
        {/* <Navbar /> */}
        {/* <Footer /> */}
        {children}
      </body>
    </html>
  );
}
